Updates and stuff

diff --git a/figma-linux/update-script b/figma-linux/update-script
--- a/figma-linux/update-script
+++ b/figma-linux/update-script
@@ -9,11 +9,14 @@ set -l url 'https://api.github.com/repos/Figma-Linux/figma-linux/releases/latest
 set -l regex 'v([\\d.]+)'
 set -l jsonpath '$.tag_name'
 
-echo 'Adding executable permissions to `parse-json`'
-chmod +x "$script_dir/../scripts/parse-json"
-
 echo 'Executing the `parse-json` script'
 set -l latest_version ("$script_dir/../scripts/parse-json" $url $regex $jsonpath)
+
+if test -z "$latest_version"
+  echo "Failed to get the latest version for '$basename'"
+  echo 'Exitting...'
+  exit 1
+end
 
 # @fish-lsp-disable-next-line 2001
 set -l current_version (sed -n 's/^Version:\\s*\\([\\d.]*\\)/\\1/p' "$script_dir/$basename.spec")
@@ -30,8 +33,5 @@ if test "$current_version" != "$latest_version"
 else
   echo 'Both versions are the same. No update needed.'
 end
-
-echo 'Removing executable permissions from `parse-json`'
-chmod -x "$script_dir/../scripts/parse-json"
 
 echo "Finished updating '$basename'"
