Update scripts
Signed-off-by: kris3713 <07e5297d5b@c0x0.com>

diff --git a/scripts/change-packages b/scripts/change-packages
--- a/scripts/change-packages
+++ b/scripts/change-packages
@@ -2,31 +2,122 @@
 
 set -l script_dir (status dirname)
 
-set -l webhook_rebuild $argv[1]
+set -l script (status filename)
 
-# echo $webhook_rebuild
+set -l msg "
+Usage:
 
-for v in (fd 'spec' "$script_dir/.." -t file --format '{}')
-  # Get subdir name (ie. the directory that contains the spec file(s))
-  set -l split_dir (string split '/' $v)
-  set -l subdir $split_dir[-2]
-  set -l name (basename -s '.spec' $split_dir[-1])
+  $script <disable-or-enable-webhook-rebuild>
 
-  echo '--------------------------------------------'
-  echo 'Clone URL: https://github.com/kris3713/figma-linux-copr.git'
-  echo 'Commitish: master'
-  echo "Subdir: $name"
-  echo "Spec: $name.spec"
-  echo "Pkg Name: $name"
-  echo "Webhook Rebuild: $webhook_rebuild"
-  echo 'COPR Project: zliced13/figma-linux'
+  OR
 
-  copr-cli edit-package-scm \
-    --clone-url 'https://github.com/kris3713/figma-linux-copr.git' \
-    --commit 'master' \
-    --subdir $subdir \
-    --spec "$name.spec" \
-    --name $name \
-    --webhook-rebuild $webhook_rebuild \
-    'zliced13/figma-linux'
+  $script <disable-or-enable-webhook-rebuild> <directory-name-relative-to-packages> <package-name>
+
+Examples:
+
+  $script on
+
+  $script off
+
+  $script on cudatext cudatext-gtk2-aarch64
+
+  $script off cudatext cudatext-gtk2-aarch64
+"
+
+switch (count $argv)
+  case 1
+    set -l webhook_rebuild $argv[1]
+
+    if test $webhook_rebuild != 'on'; and test $webhook_rebuild != 'off'
+      echo 'First argument must either be a value of "on" or "off" (without quotes)'
+      exit 1
+    end
+
+    for v in (fd 'spec' "$script_dir/.." -t file --format '{}')
+      # Get subdir name (ie. the directory that contains the spec file(s))
+      set -l split_dir (string split '/' $v)
+      set -l subdir $split_dir[-2]
+      set -l name (basename -s '.spec' $split_dir[-1])
+
+      echo '--------------------------------------------'
+      echo 'Clone URL: https://github.com/kris3713/figma-linux-copr.git'
+      echo 'Commitish: master'
+      echo "Subdir: $subdir"
+      echo "Spec: $name.spec"
+      echo "Pkg Name: $name"
+      echo "Webhook Rebuild: $webhook_rebuild"
+      echo 'COPR Project: zliced13/figma-linux'
+
+      copr-cli edit-package-scm \
+        --clone-url 'https://github.com/kris3713/figma-linux-copr.git' \
+        --commit 'master' \
+        --subdir $subdir \
+        --spec "$name.spec" \
+        --name $name \
+        --webhook-rebuild $webhook_rebuild \
+        'zliced13/figma-linux'
+    end
+
+  case 2
+    set -l webhook_rebuild $argv[1]
+    set -l name $argv[2]
+
+    if test $webhook_rebuild != 'on'; and test $webhook_rebuild != 'off'
+      echo 'First argument must either be a value of "on" or "off" (without quotes)'
+      exit 1
+    end
+
+    echo '--------------------------------------------'
+    echo 'Clone URL: https://github.com/kris3713/figma-linux-copr.git'
+    echo 'Commitish: master'
+    echo "Subdir: $name"
+    echo "Spec: $name.spec"
+    echo "Pkg Name: $name"
+    echo "Webhook Rebuild: $webhook_rebuild"
+    echo 'COPR Project: zliced13/figma-linux'
+
+    copr-cli edit-package-scm \
+      --clone-url 'https://github.com/kris3713/figma-linux-copr.git' \
+      --commit 'master' \
+      --subdir $name \
+      --spec "$name.spec" \
+      --name $name \
+      --webhook-rebuild $webhook_rebuild \
+      'zliced13/figma-linux'
+
+  case 3
+    set -l webhook_rebuild $argv[1]
+    set -l subdir $argv[2]
+    set -l name $argv[3]
+
+    if test $webhook_rebuild != 'on'; and test $webhook_rebuild != 'off'
+      echo 'First argument must either be a value of "on" or "off" (without quotes)'
+      exit 1
+    end
+
+    echo '--------------------------------------------'
+    echo 'Clone URL: https://github.com/kris3713/figma-linux-copr.git'
+    echo 'Commitish: master'
+    echo "Subdir: $subdir"
+    echo "Spec: $name.spec"
+    echo "Pkg Name: $name"
+    echo "Webhook Rebuild: $webhook_rebuild"
+    echo 'COPR Project: zliced13/figma-linux'
+
+    copr-cli edit-package-scm \
+      --clone-url 'https://github.com/kris3713/figma-linux-copr.git' \
+      --commit 'master' \
+      --subdir $subdir \
+      --spec "$name.spec" \
+      --name $name \
+      --webhook-rebuild $webhook_rebuild \
+      'zliced13/figma-linux'
+
+  case '*'
+    set_color red
+    printf 'ERROR: Invalid Usage!\n'
+    set_color normal
+
+    echo $msg
+    exit 1
 end
